backend/controllers/SideController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Side;

class SideController extends Controller
{

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['error'],
						'allow' => true,
					],
					[
						'actions' => [
							'index', 
							'single', 
							'update', 
							'delete', 
							'create'
						],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		$model = Side::find();
		return $this->render('index', [
			'model' => $model,
		]);
	}

	public function actionSingle($id) {
		$model = Side::find()->where(['id'=>$id]);
		return $this->render('index', [
			'model' => $model,
		]);
	}
	
	public function actionUpdate($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Side::findId($id);

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('update', [
			'model' => $model
		]);
	}

	public function actionCreate() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Side();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {

			$model->title = Yii::$app->request->post()['Side']['title'];
			$model->desc = Yii::$app->request->post()['Side']['desc'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('create', [
			'model' => $model,
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$model = Side::findId($id);
		$model->delete();
		return $this->redirect(['index']);
	}

}

backend/controllers/UserController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;

class UserController extends Controller
{

	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['error'],
						'allow' => true,
					],
					[
						'actions' => ['index', 'update', 'delete', 'create'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'logout' => ['post'],
				],
			],
		];
	}

	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		$model = User::find();
		return $this->render('index', [
			'model' => $model,
		]);
	}
	
	public function actionUpdate($id)
	{
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = User::findIdentity($id);

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->username = Yii::$app->request->post()['User']['username'];
			$model->email = Yii::$app->request->post()['User']['email'];
			$model->status = Yii::$app->request->post()['User']['status'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('update', [
			'model' => $model
		]);
	}

	public function actionDelete($id)
	{
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$model = User::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

}

backend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use yii\widgets\AlertLte;

?>
	  <!-- Content Wrapper. Contains page content -->
	  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
			<?php if (isset($this->blocks['content-header'])) { ?>
				<h1><?= $this->blocks['content-header'] ?></h1>
			<?php } else { ?>
				<h1>
					<?php
					if ($this->title !== null) {
						echo \yii\helpers\Html::encode($this->title);
					} else {
						echo \yii\helpers\Inflector::camel2words(
							\yii\helpers\Inflector::id2camel($this->context->module->id)
						);
						echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
					} ?>
				</h1>
			<?php } ?>

			<?=
			Breadcrumbs::widget([
				'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
			]) ?>
        </section>

        <!-- Main content -->
        <section class="content">
			<?= $content ?>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

backend/views/layouts/footer.php
	  <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2017 All rights reserved.
      </footer>

backend/views/layouts/header.php
<?php
use yii\helpers\Html;
?>
<header class="main-header">
	<!-- Logo -->
	<a href="/" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini"><b><?=$title?></b></span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg"><b><?=$title?></b> Administrator</span>
	</a>
	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top" role="navigation">
		<!-- Sidebar toggle button-->
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Навигация</span>
		</a>
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				<!-- User Account: style can be found in dropdown.less -->
				<li class="dropdown user user-menu">
					<a href="/" class="dropdown-toggle" data-toggle="dropdown">
						<?= Html::img('@web/img/user2-160x160.jpg', ['class' => 'user-image', 'alt'=>'User Image']) ?>
						<span class="hidden-xs"><?= \Yii::$app->user->identity->username ?></span>
					</a>
					<ul class="dropdown-menu">
						<!-- User image -->
						<li class="user-header">
							<?= Html::img('@web/img/user2-160x160.jpg', ['class' => 'img-circle', 'alt'=>'User Image']) ?>
							<p>
								<?= \Yii::$app->user->identity->username ?> - The Супер Юзер
								<small></small>
							</p>
						</li>
						<!-- Menu Footer-->
						<li class="user-footer">
							<div class="pull-right">
								<a href="/admin/site/logout" class="btn btn-default btn-flat">Выход</a>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>

backend/views/layouts/leftside.php
<?php

use adminlte\widgets\Menu;
use yii\helpers\Html;
use yii\helpers\Url;
?>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- Sidebar user panel -->
		<div class="user-panel">
			<div class="pull-left image">
				<?= Html::img('@web/img/user2-160x160.jpg', ['class' => 'img-circle', 'alt' => 'User Image']) ?>
			</div>
			<div class="pull-left info">
				<p><?= \Yii::$app->user->identity->username ?></p>
				<a href=""><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>
		<!-- sidebar menu: : style can be found in sidebar.less -->
		<?=
		Menu::widget(
				[
					'options' => ['class' => 'sidebar-menu'],
					'items' => [
						['label' => 'Menu', 'options' => ['class' => 'header']],
						['label' => 'Сайт', 'icon' => 'fa fa-home', 
							'url' => ['../'],
						],
						['label' => 'Список выборов', 'icon' => 'fa fa-dashboard', 
							'url' => ['/'], 'active' => $this->context->route == 'site/index'
						],
						['label' => 'Кандидаты', 'icon' => 'fa fa-users', 
							'url' => ['/side'], 'active' => $this->context->route == 'side/index'
						],
						[
							'label' => 'Пользователи', 'icon' => 'fa fa-users',
							'url' => ['/user'], 'active' => $this->context->route == 'user/index',
						],
					],
				]
		)
		?>
		
	</section>
	<!-- /.sidebar -->
</aside>

backend/views/layouts/login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use backend\assets\AdminLteAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use backend\assets\AppAsset;
use backend\assets\AdminLteAsset;

//AppAsset::register($this);
$asset      = AdminLteAsset::register($this);
$baseUrl    = $asset->baseUrl;

use backend\assets\FontAwesomeAsset;
FontAwesomeAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>

<div class="wrapper">
    <?= $this->render('header.php', ['baserUrl' => $baseUrl, 'title'=>Yii::$app->name]) ?>
    <?= $this->render('leftside.php', ['baserUrl' => $baseUrl]) ?>
    <?= $this->render('content.php', ['content' => $content]) ?>
    <?= $this->render('footer.php', ['baserUrl' => $baseUrl]) ?>
    <?= $this->render('rightside.php', ['baserUrl' => $baseUrl]) ?>
</div>

<!--footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?//= date('Y') ?></p>

        <p class="pull-right"><?//= Yii::powered() ?></p>
    </div>
</footer-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>